In [8]:
# parameters
import torch
import torch.nn as nn
import math

BATCH_SIZE = 2
CHANNEL_IN = 3
CHANNEL_OUT = 3
HEIGHT_IN = 4
WIDTH_IN = 4

KERNEL_SIZE = 3
STRIDE = 1
GROUP = 1
PADDING = math.ceil((KERNEL_SIZE - STRIDE) / 2)
EPS = 1e-5

HEIGHT_OUT = int((HEIGHT_IN - KERNEL_SIZE + 2 * PADDING) / STRIDE + 1)
WIDTH_OUT = int((WIDTH_IN - KERNEL_SIZE + 2 * PADDING) / STRIDE + 1)

In [9]:
# convolution
x = torch.zeros(BATCH_SIZE, CHANNEL_IN, HEIGHT_IN, WIDTH_IN)

for n in range(BATCH_SIZE):
    for c in range(CHANNEL_IN):
        for h in range(HEIGHT_IN):
            for w in range(WIDTH_IN):
                x[n, c, h, w] = h + c

KERNEL_CHANNEL = int(CHANNEL_IN / GROUP)
kernel = torch.zeros((CHANNEL_OUT, KERNEL_CHANNEL, KERNEL_SIZE, KERNEL_SIZE))
for k in range(CHANNEL_OUT):
    for l in range(KERNEL_CHANNEL):
        for i in range(KERNEL_SIZE):
            for j in range(KERNEL_SIZE):
                kernel[k, l, i, j] = j + k

bias = torch.zeros((CHANNEL_OUT,))
for c in range(CHANNEL_OUT):
    bias[c] = c + 10

conv = torch.nn.Conv2d(in_channels=CHANNEL_IN, out_channels=CHANNEL_OUT,
                       kernel_size=KERNEL_SIZE, bias=True, stride=STRIDE, padding=PADDING, groups=GROUP)
conv.weight.data = kernel
conv.bias.data = bias

afterConv = conv(x)

print("afterConv shape: ", afterConv.shape)
print(afterConv[0, 0, :, :])

afterConv shape:  torch.Size([2, 3, 4, 4])
tensor([[37., 37., 37., 19.],
        [64., 64., 64., 28.],
        [91., 91., 91., 37.],
        [73., 73., 73., 31.]], grad_fn=<SliceBackward0>)


In [10]:
# batch normalization
# shape of running_mean and running_var should be same as channel_outs
RUNNING_MEAN = [ 82, 227, 444]
RUNNING_VAR = [ 945, 3780, 8505]
weight = [0.5, 0.5, 0.5]
bias = [0.2, 0.2, 0.2]
momentum = 0
eps = 1e-5

batch_norm = nn.BatchNorm2d(num_features=CHANNEL_OUT,momentum=momentum, eps=eps)
batch_norm.running_mean = torch.tensor(RUNNING_MEAN, dtype=torch.float)
batch_norm.running_var = torch.tensor(RUNNING_VAR, dtype=torch.float)
batch_norm.weight.data = torch.tensor(weight, dtype=torch.float)
batch_norm.bias.data = torch.tensor(bias, dtype=torch.float)

batch_norm.eval()
afterNorm = batch_norm(afterConv)

print("BN output:")
# print("running_mean:", batch_norm.running_mean)
# print("running_var:",batch_norm.running_var)
# print("weight:",batch_norm.weight)
# print("bias:",batch_norm.bias)
print(afterNorm.shape)
print(afterNorm[0, 0, :, :])

BN output:
torch.Size([2, 3, 4, 4])
tensor([[-0.5319, -0.5319, -0.5319, -0.8247],
        [-0.0928, -0.0928, -0.0928, -0.6783],
        [ 0.3464,  0.3464,  0.3464, -0.5319],
        [ 0.0536,  0.0536,  0.0536, -0.6295]], grad_fn=<SliceBackward0>)


In [80]:
normalize_shape = (HEIGHT_OUT, WIDTH_OUT, CHANNEL_OUT)
weight = torch.zeros(normalize_shape)
bias = torch.zeros(normalize_shape)

for h in range(HEIGHT_OUT):
    for w in range(WIDTH_OUT):
        for c in range(CHANNEL_OUT):
            weight[h, w, c] = h
            bias[h, w, c] = w
            
ln_in = afterConv.permute(0, 2, 3, 1)

ln_norm = nn.LayerNorm([HEIGHT_OUT, WIDTH_OUT, CHANNEL_OUT], eps=EPS, elementwise_affine=True)
ln_norm.weight.data = weight
ln_norm.bias.data = bias
print("weight shape: ", ln_norm.weight.shape)
print("bias shape: ", ln_norm.bias.shape)

ln_out = ln_norm(ln_in)
afterNorm = ln_out.permute(0, 3, 1, 2)
print("LN Out:")
print(afterNorm[0, 0, :, :])

weight shape:  torch.Size([4, 4, 3])
bias shape:  torch.Size([4, 4, 3])
LN Out:
tensor([[ 0.0000,  1.0000,  2.0000,  3.0000],
        [-0.6973,  0.3027,  1.3027,  1.6866],
        [-0.4706,  0.5294,  1.5294,  0.6812],
        [-1.6300, -0.6300,  0.3700, -0.7862]], grad_fn=<SliceBackward0>)


In [11]:
# relu
relu = nn.ReLU()
out = relu(afterNorm)

print(out[0, 0, :, :])

tensor([[0.0000, 0.0000, 0.0000, 0.0000],
        [0.0000, 0.0000, 0.0000, 0.0000],
        [0.3464, 0.3464, 0.3464, 0.0000],
        [0.0536, 0.0536, 0.0536, 0.0000]], grad_fn=<SliceBackward0>)


In [83]:
# silu
silu = nn.SiLU()
out = silu(afterNorm)

print(out[0, 0, :, :])

tensor([[-0.1968, -0.1968, -0.1968, -0.2513],
        [-0.0442, -0.0442, -0.0442, -0.2283],
        [ 0.2029,  0.2029,  0.2029, -0.1968],
        [ 0.0275,  0.0275,  0.0275, -0.2188]], grad_fn=<SliceBackward0>)


In [84]:
# gelu
gelu = nn.functional.gelu
out = gelu(afterNorm)

print(out[0, 0, :, :])

tensor([[-0.1582, -0.1582, -0.1582, -0.1689],
        [-0.0430, -0.0430, -0.0430, -0.1688],
        [ 0.2201,  0.2201,  0.2201, -0.1582],
        [ 0.0280,  0.0280,  0.0280, -0.1665]], grad_fn=<SliceBackward0>)


In [12]:
# shortcut
out = out + x

print(out[0, 0, :, :])

tensor([[0.0000, 0.0000, 0.0000, 0.0000],
        [1.0000, 1.0000, 1.0000, 1.0000],
        [2.3464, 2.3464, 2.3464, 2.0000],
        [3.0536, 3.0536, 3.0536, 3.0000]], grad_fn=<SliceBackward0>)
